# -*- coding: utf-8 -*-
"""Weather Automation tool V2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eqh9dHktt8BKzSOqfOwsCj__IzA3Cfai
"""

# weather_tool_v2.py
# Weather Automation Tool (Version 2 - Live Weather API)

import requests

API_KEY = "040ab350086be1fa151fb2fe834065b8"  # replace with your OpenWeatherMap key
BASE_URL = "https://api.openweathermap.org/data/2.5/weather"

def get_weather(city):
    params = {
        "q": city,
        "appid": API_KEY,
        "units": "metric"  # for Celsius
    }
    response = requests.get(BASE_URL, params=params)

    if response.status_code == 200:
        data = response.json()
        weather = {
            "temperature": data["main"]["temp"],
            "condition": data["weather"][0]["description"].title(),
            "humidity": data["main"]["humidity"]
        }
        return weather
    else:
        return None

def main():
    print("🌦️ Weather Automation Tool (V2 - Live API)")
    city = input("Enter a city name: ")

    weather = get_weather(city)

    if weather:
        print(f"\nWeather Report for {city}:")
        print(f"Temperature: {weather['temperature']}°C")
        print(f"Condition: {weather['condition']}")
        print(f"Humidity: {weather['humidity']}%")
    else:
        print("⚠️ Could not fetch weather data. Please check the city name or try again later.")

if __name__ == "__main__":
    main()